[package]
name = "day03"
version = "0.1.0"
authors = ["Konrad <szymoniak.konrad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"
itertools = "0.9.0"
